scene:
  data_path: "data/truck/"
  output_path: "results/truck/"
  exp_name: "exp_debug"
  type: "colmap"

training_params:
  iterations: 30000
  position_lr_init: 0.00008
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.025
  scaling_lr: 0.005
  rotation_lr: 0.001
  lambda_dssim: 0.2
  lambda_depth: 0.0
  optimizer_type: "default"
  opacity_reset_interval: 3000
  preload: False  # False:disk / True:cpu
  densification_interval: 200
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0004
  percent_dense: 0.01
  log: True
  log_interval: 100
  image_log_interval:500
  eval: True
  eval_interval: 3000

renderer_params:
  renderer_type: "gsplat"

model_params:
  image_scale: 1.0
  scene_scale: 1.0
  spherical_harmonics: True
  sh_degree: 3
  max_num_gaussians: 10000000
